=== StudyInParis/crispy-carnival/grammaires/distributeurspreservatifsmasculinsparis2012.dtd
<!ELEMENT root (n24, n4, n11, n3, n27, n15, n1, n25, n31, n29, n18, n17, n20, n8, n5, n28, n2, n16, n10, n13, n26, n9, n12, n7, n6, n23, n14, n30, n22, n21, n19)>
<!ELEMENT n24 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n24
          id CDATA #REQUIRED>
<!ELEMENT acces (#PCDATA)>
<!ATTLIST acces
          id CDATA #REQUIRED>
<!ELEMENT annee_installation (#PCDATA)>
<!ATTLIST annee_installation
          id CDATA #REQUIRED>
<!ELEMENT adresse_complete (#PCDATA)>
<!ATTLIST adresse_complete
          id CDATA #REQUIRED>
<!ELEMENT adresse (#PCDATA)>
<!ATTLIST adresse
          id CDATA #REQUIRED>
<!ELEMENT horaires_normal (#PCDATA)>
<!ATTLIST horaires_normal
          id CDATA #REQUIRED>
<!ELEMENT horaires_vacances_hiver (#PCDATA)>
<!ATTLIST horaires_vacances_hiver
          id CDATA #REQUIRED>
<!ELEMENT horaires_vacances_ete (#PCDATA)>
<!ATTLIST horaires_vacances_ete
          id CDATA #REQUIRED>
<!ELEMENT site (#PCDATA)>
<!ATTLIST site
          id CDATA #REQUIRED>
<!ELEMENT xy (item+)>
<!ATTLIST xy
          id CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
          id CDATA #REQUIRED>
<!ELEMENT arrond (#PCDATA)>
<!ATTLIST arrond
          id CDATA #REQUIRED>
<!ELEMENT n4 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n4
          id CDATA #REQUIRED>
<!ELEMENT n11 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n11
          id CDATA #REQUIRED>
<!ELEMENT n3 (acces, arrond, adresse_complete, adresse, horaires_vacances_hiver, annee_installation, site, xy)>
<!ATTLIST n3
          id CDATA #REQUIRED>
<!ELEMENT n27 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n27
          id CDATA #REQUIRED>
<!ELEMENT n15 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n15
          id CDATA #REQUIRED>
<!ELEMENT n1 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n1
          id CDATA #REQUIRED>
<!ELEMENT n25 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n25
          id CDATA #REQUIRED>
<!ELEMENT n31 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n31
          id CDATA #REQUIRED>
<!ELEMENT n29 (acces, annee_installation, adresse_complete, adresse, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n29
          id CDATA #REQUIRED>
<!ELEMENT n18 (acces, annee_installation, adresse_complete, adresse, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n18
          id CDATA #REQUIRED>
<!ELEMENT n17 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n17
          id CDATA #REQUIRED>
<!ELEMENT n20 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n20
          id CDATA #REQUIRED>
<!ELEMENT n8 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n8
          id CDATA #REQUIRED>
<!ELEMENT n5 (acces, arrond, adresse_complete, adresse, horaires_vacances_hiver, annee_installation, site, xy)>
<!ATTLIST n5
          id CDATA #REQUIRED>
<!ELEMENT n28 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n28
          id CDATA #REQUIRED>
<!ELEMENT n2 (acces, arrond, adresse_complete, adresse, annee_installation, site, xy)>
<!ATTLIST n2
          id CDATA #REQUIRED>
<!ELEMENT n16 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n16
          id CDATA #REQUIRED>
<!ELEMENT n10 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n10
          id CDATA #REQUIRED>
<!ELEMENT n13 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n13
          id CDATA #REQUIRED>
<!ELEMENT n26 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n26
          id CDATA #REQUIRED>
<!ELEMENT n9 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n9
          id CDATA #REQUIRED>
<!ELEMENT n12 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n12
          id CDATA #REQUIRED>
<!ELEMENT n7 (acces, arrond, adresse_complete, adresse, horaires_vacances_hiver, annee_installation, site, xy, horaires_normal)>
<!ATTLIST n7
          id CDATA #REQUIRED>
<!ELEMENT n6 (acces, arrond, adresse_complete, adresse, horaires_vacances_hiver, annee_installation, site, xy, horaires_normal)>
<!ATTLIST n6
          id CDATA #REQUIRED>
<!ELEMENT n23 (acces, arrond, adresse_complete, adresse, horaires_vacances_hiver, annee_installation, site, xy, horaires_normal)>
<!ATTLIST n23
          id CDATA #REQUIRED>
<!ELEMENT n14 (acces, arrond, adresse_complete, adresse, horaires_vacances_hiver, annee_installation, site, xy, horaires_normal)>
<!ATTLIST n14
          id CDATA #REQUIRED>
<!ELEMENT n30 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n30
          id CDATA #REQUIRED>
<!ELEMENT n22 (acces, arrond, adresse_complete, adresse, annee_installation, site, xy)>
<!ATTLIST n22
          id CDATA #REQUIRED>
<!ELEMENT n21 (acces, arrond, adresse_complete, adresse, annee_installation, site, xy)>
<!ATTLIST n21
          id CDATA #REQUIRED>
<!ELEMENT n19 (acces, annee_installation, adresse_complete, adresse, horaires_normal, horaires_vacances_hiver, horaires_vacances_ete, site, xy, arrond)>
<!ATTLIST n19
          id CDATA #REQUIRED>

=== StudyInParis/crispy-carnival/donnees_brutes/distributeurspreservatifsmasculinsparis2012.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root SYSTEM "distributeurspreservatifsmasculinsparis2012.dtd">
<root><n24 id="root_213888"><annee_installation id="n24_561680">2008/2009</annee_installation><horaires_vacances_ete id="n24_735667">7h à 15h</horaires_vacances_ete><adresse id="n24_217216">26 rue Buffault</adresse><site id="n24_643219">Gymnase Buffault</site><horaires_vacances_hiver id="n24_473495">9h à 22h30</horaires_vacances_hiver><acces id="n24_859434">Intérieur</acces><xy id="n24_382203"><item id="xy_520202_1">48.87601</item><item id="xy_520202_2">2.342244</item></xy><adresse_complete id="n24_169558">26 rue Buffault 75009 Paris  France</adresse_complete><arrond id="n24_891337">75009</arrond><horaires_normal id="n24_714639">9h à 22h30</horaires_normal></n24><n25 id="root_268328"><annee_installation id="n25_282424">2008/2009</annee_installation><horaires_vacances_ete id="n25_531616">8h à 22h</horaires_vacances_ete><adresse id="n25_482888">7-15 Av Paul Appell</adresse><site id="n25_979391">Centre sportif Elisabeth</site><horaires_vacances_hiver id="n25_560095">8h à 22h30</horaires_vacances_hiver><acces id="n25_589005">Intérieur</acces><xy id="n25_917550"><item id="xy_806116_1">48.821057</item><item id="xy_806116_2">2.329049</item></xy><adresse_complete id="n25_971600">7-15 Av Paul Appell 75014 Paris  France</adresse_complete><arrond id="n25_340140">75014</arrond><horaires_normal id="n25_233681">8h à 22h30</horaires_normal></n25><n26 id="root_791080"><annee_installation id="n26_795007">2008/2009</annee_installation><horaires_vacances_ete id="n26_598083">8h à 18h</horaires_vacances_ete><adresse id="n26_732180">56 Bd de l&apos;Amiral Bruix</adresse><site id="n26_717284">Stade Jean Pierre Wimille</site><horaires_vacances_hiver id="n26_478679">fermé</horaires_vacances_hiver><acces id="n26_853252">Intérieur</acces><xy id="n26_351157"><item id="xy_968005_1">48.873512</item><item id="xy_968005_2">2.276701</item></xy><adresse_complete id="n26_714361">56 Bd de l&apos;Amiral Bruix 75016 Paris  France</adresse_complete><arrond id="n26_624368">75016</arrond><horaires_normal id="n26_126875">7h à 22h30</horaires_normal></n26><n27 id="root_449448"><annee_installation id="n27_731595">2008/2009</annee_installation><horaires_vacances_ete id="n27_274589">7h à 20h</horaires_vacances_ete><adresse id="n27_729967">Place de la Porte de Pantin</adresse><site id="n27_807467">Centre sportif Jules Ladoumègue</site><horaires_vacances_hiver id="n27_160483">8h à 22h</horaires_vacances_hiver><acces id="n27_979427">Intérieur</acces><xy id="n27_209074"><item id="xy_585070_1">48.889698</item><item id="xy_585070_2">2.395738</item></xy><adresse_complete id="n27_419870">Place de la Porte de Pantin 75019 Paris  France</adresse_complete><arrond id="n27_332070">75019</arrond><horaires_normal id="n27_163836">8h à 22h</horaires_normal></n27><n20 id="root_828870"><annee_installation id="n20_596155">2010</annee_installation><horaires_vacances_ete id="n20_823322">10h à 18h</horaires_vacances_ete><adresse id="n20_789350">101 Quai Branly</adresse><site id="n20_967544">Kiosque jeunes Champ de Mars</site><horaires_vacances_hiver id="n20_494301">10h à 18h</horaires_vacances_hiver><acces id="n20_341871">Intérieur</acces><xy id="n20_255184"><item id="xy_233598_1">48.855739</item><item id="xy_233598_2">2.290049</item></xy><adresse_complete id="n20_126709">101 Quai Branly 75015 Paris  France</adresse_complete><arrond id="n20_257778">75015</arrond><horaires_normal id="n20_111452">10h à 18h</horaires_normal></n20><n21 id="root_291569"><adresse id="n21_582451">32 rue du Javelot Tour Anvers</adresse><site id="n21_235753">Antenne jeunes Olympiades</site><annee_installation id="n21_933306">2010</annee_installation><acces id="n21_296096">Extérieur</acces><xy id="n21_542724"><item id="xy_510272_1">48.823105</item><item id="xy_510272_2">2.36651</item></xy><adresse_complete id="n21_721878">32 rue du Javelot Tour Anvers 75013 Paris  France</adresse_complete><arrond id="n21_443061">75013</arrond></n21><n22 id="root_295172"><adresse id="n22_184421">43 rue de l&apos;Orillon</adresse><site id="n22_311632">Antenne jeunes Orillon</site><annee_installation id="n22_428711">2010</annee_installation><acces id="n22_344277">Extérieur</acces><xy id="n22_618253"><item id="xy_252973_1">48.870547</item><item id="xy_252973_2">2.377314</item></xy><adresse_complete id="n22_660996">43 rue de l&apos;Orillon 75011 Paris  France</adresse_complete><arrond id="n22_660928">75011</arrond></n22><n23 id="root_328905"><annee_installation id="n23_620034">2010</annee_installation><adresse id="n23_252653">2/4 rue des Lilas</adresse><site id="n23_106392">Centre d&apos;animation Place des Fêtes</site><horaires_vacances_hiver id="n23_212960">fermé</horaires_vacances_hiver><acces id="n23_517162">Intérieur</acces><xy id="n23_487706"><item id="xy_767352_1">48.877942</item><item id="xy_767352_2">2.395611</item></xy><adresse_complete id="n23_942787">2/4 rue des Lilas 75019 Paris  France</adresse_complete><arrond id="n23_949281">75019</arrond><horaires_normal id="n23_991915">11h à 22h</horaires_normal></n23><n28 id="root_577816"><annee_installation id="n28_673177">2008/2009</annee_installation><horaires_vacances_ete id="n28_912547">8h à 17h</horaires_vacances_ete><adresse id="n28_808259">87 Av J.Jaurès</adresse><site id="n28_839601">Gymnase Jean Jaurès</site><horaires_vacances_hiver id="n28_188282">fermé</horaires_vacances_hiver><acces id="n28_871462">Intérieur</acces><xy id="n28_342983"><item id="xy_959099_1">48.885151</item><item id="xy_959099_2">2.379099</item></xy><adresse_complete id="n28_317796">87 Av J.Jaurès 75019 Paris  France</adresse_complete><arrond id="n28_882677">75019</arrond><horaires_normal id="n28_137050">7h à 22h30</horaires_normal></n28><n29 id="root_201024"><annee_installation id="n29_143778">2010</annee_installation><horaires_vacances_ete id="n29_282932">14h à 19h</horaires_vacances_ete><adresse id="n29_135624">49 ter Av de Flandre</adresse><site id="n29_786347">Antenne jeunes Flandre</site><horaires_vacances_hiver id="n29_790902">14h à 19h</horaires_vacances_hiver><acces id="n29_945589">Intérieur</acces><xy id="n29_774596"><item id="xy_673226_1">48.887097</item><item id="xy_673226_2">2.372115</item></xy><adresse_complete id="n29_360902">49 ter Av de Flandre 75019 Paris  France</adresse_complete><arrond id="n29_329568">75019</arrond></n29><n1 id="root_464176"><annee_installation id="n1_364073">2008/2009</annee_installation><horaires_vacances_ete id="n1_214350">8h à 22h</horaires_vacances_ete><adresse id="n1_627875">3 Av Maurice D&apos;Ocagne</adresse><site id="n1_778373">Centre sportif Jules Noël</site><horaires_vacances_hiver id="n1_522258">9h à 22h30</horaires_vacances_hiver><acces id="n1_659957">Intérieur</acces><xy id="n1_348111"><item id="xy_984603_1">48.824547</item><item id="xy_984603_2">2.314142</item></xy><adresse_complete id="n1_373072">3 Av Maurice D&apos;Ocagne 75014 Paris  France</adresse_complete><arrond id="n1_825735">75014</arrond><horaires_normal id="n1_797677">8h à 22h30</horaires_normal></n1><n3 id="root_863058"><annee_installation id="n3_763346">2010</annee_installation><adresse id="n3_942708">1 rue Fleury Centre Musical</adresse><site id="n3_157662">Kiosque jeunes Goutte D&apos;Or</site><horaires_vacances_hiver id="n3_529946">fermé</horaires_vacances_hiver><acces id="n3_242184">Intérieur</acces><xy id="n3_186517"><item id="xy_718809_1">48.884298</item><item id="xy_718809_2">2.354045</item></xy><adresse_complete id="n3_393251">1 rue Fleury Centre Musical 75018 Paris  France</adresse_complete><arrond id="n3_518686">75018</arrond></n3><n2 id="root_653446"><adresse id="n2_917340">2 rue Jean Cocteau</adresse><site id="n2_405142">Centre sportif Poissonniers</site><annee_installation id="n2_812457">2008/2009</annee_installation><acces id="n2_198341">Extérieur</acces><xy id="n2_242951"><item id="xy_766500_1">48.89968</item><item id="xy_766500_2">2.352224</item></xy><adresse_complete id="n2_209190">2 rue Jean Cocteau 75018 Paris  France</adresse_complete><arrond id="n2_137889">75018</arrond></n2><n5 id="root_752478"><annee_installation id="n5_917856">2008/2009</annee_installation><adresse id="n5_860339">34 rue des docteurs Déjérine</adresse><site id="n5_190685">Centre sportif Déjérine</site><horaires_vacances_hiver id="n5_980963">fermé</horaires_vacances_hiver><acces id="n5_874638">Intérieur</acces><xy id="n5_460697"><item id="xy_630890_1">48.856657</item><item id="xy_630890_2">2.411711</item></xy><adresse_complete id="n5_896009">34 rue des docteurs Déjérine 75020 Paris  France</adresse_complete><arrond id="n5_618758">75020</arrond></n5><n4 id="root_678734"><annee_installation id="n4_170288">2008/2009</annee_installation><horaires_vacances_ete id="n4_565978">8h à 22h</horaires_vacances_ete><adresse id="n4_729082">81 Bd Masséna</adresse><site id="n4_379872">Centre sportif Georges Carpentier</site><horaires_vacances_hiver id="n4_990419">8h à 22h</horaires_vacances_hiver><acces id="n4_880576">Intérieur</acces><xy id="n4_488328"><item id="xy_481654_1">48.820839</item><item id="xy_481654_2">2.368247</item></xy><adresse_complete id="n4_914711">81 Bd Masséna 75013 Paris  France</adresse_complete><arrond id="n4_707918">75013</arrond><horaires_normal id="n4_577407">8h à 22h</horaires_normal></n4><n7 id="root_755814"><annee_installation id="n7_918871">2010</annee_installation><adresse id="n7_434409">6 rue de la Goutte d&apos;Or</adresse><site id="n7_677353">Espace jeunes Goutte D&apos;Or</site><horaires_vacances_hiver id="n7_482989">14h à 21h</horaires_vacances_hiver><acces id="n7_669009">Intérieur</acces><xy id="n7_729188"><item id="xy_393278_1">48.885028</item><item id="xy_393278_2">2.354614</item></xy><adresse_complete id="n7_507191">6 rue de la Goutte d&apos;Or 75018 Paris  France</adresse_complete><arrond id="n7_679488">75018</arrond><horaires_normal id="n7_542316">14h à 21h</horaires_normal></n7><n6 id="root_427095"><annee_installation id="n6_364504">2010</a
